### ISSUE TITLE
Poor default location for stunnel.pid

### ISSUE THREAD

**Issue by jhmartin** [sous-chefs/chef-stunnel#28]
The default location for the stunnel pidfile is /tmp which gets removed by most distributions /tmp cleanup, causing chef to fail after several days when this file gets removed.  

Chef fails with:

```
STDOUT: Starting SSL tunnels: [Failed: /etc/stunnel/stunnel.conf] You should check that you have specified the pid= in you configuration file
```

**Comment by martinisoft** [comment]
Hi @jhmartin 

I realize this might be way past due for a response, but I'd like to know if you have any suggestions on a better location? My guess is somewhere under `/var/run` over `/tmp`

**Comment by rambler** [comment]
+1 for /var/run

**Comment by rubeon** [comment]
Most distributions migrated to /run instead of /var/run, but symlink /run -> /var/run . I figure that's going away at some point.

I've found it necessary to do some sniffing to see where the files are expected.

```
if /run exists 
  /run
else if /var/run/ exists
  /var/run
else 
  /tmp # why not
end

```
Blame Lennart :-/
FHS 3.0 http://refspecs.linuxfoundation.org/FHS_3.0/fhs/ch03s15.html

**Comment by martinisoft** [comment]
@rubeon I'd agree with you on the `/run` directory being a sensible default via an attribute so it is easily tunable.

**Comment by jhmartin** [comment]
Looks like https://github.com/sous-chefs/chef-stunnel/pull/33 fixed this.

**Comment by jhmartin** [comment]
Oops that was closed, not merged.
